laBilletterieBackOffice/src/java/entityDB/TicketController.java
package entityDB;

import entityDB.util.JsfUtil;
import entityDB.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("ticketController")
@SessionScoped
public class TicketController implements Serializable {

    private Ticket current;
    private DataModel items = null;
    @EJB
    private entityDB.TicketFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TicketController() {
    }

    public Ticket getSelected() {
        if (current == null) {
            current = new Ticket();
            selectedItemIndex = -1;
        }
        return current;
    }

    private TicketFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Ticket) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Ticket();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TicketCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Ticket) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TicketUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Ticket) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TicketDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Ticket getTicket(java.math.BigDecimal id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Ticket.class)
    public static class TicketControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TicketController controller = (TicketController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "ticketController");
            return controller.getTicket(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Ticket) {
                Ticket o = (Ticket) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Ticket.class.getName());
            }
        }

    }

}

laBilletterieBackOffice/web/pageJSF/ticket/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateTicketTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateTicketLabel_id}" for="id" />
                    <h:inputText id="id" value="#{ticketController.selected.id}" title="#{bundle.CreateTicketTitle_id}" required="false" requiredMessage="#{bundle.CreateTicketRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateTicketLabel_ETicket}" for="ETicket" />
                    <h:inputText id="ETicket" value="#{ticketController.selected.ETicket}" title="#{bundle.CreateTicketTitle_ETicket}" />
                    <h:outputLabel value="#{bundle.CreateTicketLabel_numero}" for="numero" />
                    <h:inputText id="numero" value="#{ticketController.selected.numero}" title="#{bundle.CreateTicketTitle_numero}" />
                    <h:outputLabel value="#{bundle.CreateTicketLabel_suppressionLogique}" for="suppressionLogique" />
                    <h:inputText id="suppressionLogique" value="#{ticketController.selected.suppressionLogique}" title="#{bundle.CreateTicketTitle_suppressionLogique}" />
                    <h:outputLabel value="#{bundle.CreateTicketLabel_seanceId}" for="seanceId" />
                    <h:selectOneMenu id="seanceId" value="#{ticketController.selected.seanceId}" title="#{bundle.CreateTicketTitle_seanceId}" >
                        <f:selectItems value="#{seanceController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateTicketLabel_placeId}" for="placeId" />
                    <h:selectOneMenu id="placeId" value="#{ticketController.selected.placeId}" title="#{bundle.CreateTicketTitle_placeId}" >
                        <f:selectItems value="#{placeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateTicketLabel_commandeId}" for="commandeId" />
                    <h:selectOneMenu id="commandeId" value="#{ticketController.selected.commandeId}" title="#{bundle.CreateTicketTitle_commandeId}" >
                        <f:selectItems value="#{commandeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{ticketController.create}" value="#{bundle.CreateTicketSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{ticketController.prepareList}" value="#{bundle.CreateTicketShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateTicketIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

laBilletterieBackOffice/web/pageJSF/ticket/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditTicketTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditTicketLabel_id}" for="id" />
                    <h:inputText id="id" value="#{ticketController.selected.id}" title="#{bundle.EditTicketTitle_id}" required="true" requiredMessage="#{bundle.EditTicketRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditTicketLabel_ETicket}" for="ETicket" />
                    <h:inputText id="ETicket" value="#{ticketController.selected.ETicket}" title="#{bundle.EditTicketTitle_ETicket}" />
                    <h:outputLabel value="#{bundle.EditTicketLabel_numero}" for="numero" />
                    <h:inputText id="numero" value="#{ticketController.selected.numero}" title="#{bundle.EditTicketTitle_numero}" />
                    <h:outputLabel value="#{bundle.EditTicketLabel_suppressionLogique}" for="suppressionLogique" />
                    <h:inputText id="suppressionLogique" value="#{ticketController.selected.suppressionLogique}" title="#{bundle.EditTicketTitle_suppressionLogique}" />
                    <h:outputLabel value="#{bundle.EditTicketLabel_seanceId}" for="seanceId" />
                    <h:selectOneMenu id="seanceId" value="#{ticketController.selected.seanceId}" title="#{bundle.EditTicketTitle_seanceId}" >
                        <f:selectItems value="#{seanceController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditTicketLabel_placeId}" for="placeId" />
                    <h:selectOneMenu id="placeId" value="#{ticketController.selected.placeId}" title="#{bundle.EditTicketTitle_placeId}" >
                        <f:selectItems value="#{placeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditTicketLabel_commandeId}" for="commandeId" />
                    <h:selectOneMenu id="commandeId" value="#{ticketController.selected.commandeId}" title="#{bundle.EditTicketTitle_commandeId}" >
                        <f:selectItems value="#{commandeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{ticketController.update}" value="#{bundle.EditTicketSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditTicketViewLink}"/>
                <br />
                <h:commandLink action="#{ticketController.prepareList}" value="#{bundle.EditTicketShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditTicketIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

laBilletterieBackOffice/web/pageJSF/ticket/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTicketTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListTicketEmpty}" rendered="#{ticketController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{ticketController.items.rowCount > 0}">
                    <h:outputText value="#{ticketController.pagination.pageFirstItem + 1}..#{ticketController.pagination.pageLastItem + 1}/#{ticketController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{ticketController.previous}" value="#{bundle.Previous} #{ticketController.pagination.pageSize}" rendered="#{ticketController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{ticketController.next}" value="#{bundle.Next} #{ticketController.pagination.pageSize}" rendered="#{ticketController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{ticketController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_ETicket}"/>
                            </f:facet>
                            <h:outputText value="#{item.ETicket}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_numero}"/>
                            </f:facet>
                            <h:outputText value="#{item.numero}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_suppressionLogique}"/>
                            </f:facet>
                            <h:outputText value="#{item.suppressionLogique}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_seanceId}"/>
                            </f:facet>
                            <h:outputText value="#{item.seanceId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_placeId}"/>
                            </f:facet>
                            <h:outputText value="#{item.placeId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTicketTitle_commandeId}"/>
                            </f:facet>
                            <h:outputText value="#{item.commandeId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{ticketController.prepareView}" value="#{bundle.ListTicketViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ticketController.prepareEdit}" value="#{bundle.ListTicketEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ticketController.destroy}" value="#{bundle.ListTicketDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{ticketController.prepareCreate}" value="#{bundle.ListTicketCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTicketIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

laBilletterieBackOffice/web/pageJSF/ticket/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewTicketTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewTicketLabel_id}"/>
                    <h:outputText value="#{ticketController.selected.id}" title="#{bundle.ViewTicketTitle_id}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_ETicket}"/>
                    <h:outputText value="#{ticketController.selected.ETicket}" title="#{bundle.ViewTicketTitle_ETicket}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_numero}"/>
                    <h:outputText value="#{ticketController.selected.numero}" title="#{bundle.ViewTicketTitle_numero}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_suppressionLogique}"/>
                    <h:outputText value="#{ticketController.selected.suppressionLogique}" title="#{bundle.ViewTicketTitle_suppressionLogique}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_seanceId}"/>
                    <h:outputText value="#{ticketController.selected.seanceId}" title="#{bundle.ViewTicketTitle_seanceId}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_placeId}"/>
                    <h:outputText value="#{ticketController.selected.placeId}" title="#{bundle.ViewTicketTitle_placeId}"/>
                    <h:outputText value="#{bundle.ViewTicketLabel_commandeId}"/>
                    <h:outputText value="#{ticketController.selected.commandeId}" title="#{bundle.ViewTicketTitle_commandeId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{ticketController.destroyAndView}" value="#{bundle.ViewTicketDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewTicketEditLink}"/>
                <br />
                <h:commandLink action="#{ticketController.prepareCreate}" value="#{bundle.ViewTicketCreateLink}" />
                <br />
                <h:commandLink action="#{ticketController.prepareList}" value="#{bundle.ViewTicketShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewTicketIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>